apiVersion: v1
kind: Secret
metadata:
  name: csi-cephfs-secret
  namespace: default
data:
  userID: cnZhc2VrLXNoYXJlLXVzZXI=
  userKey: QVFBazNLdGFVNVpqTlJBQU4vdjJrd0JnelVNVlh4ODRGa3dUQmc9PQ==

  adminID: YWRtaW4=
  adminKey: QVFDZHNwOWFhb3dxRWhBQUh4NUVGblRRQm5UVTdEcjFVekh3bVE9PQ==