apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-cvmfs-atlas
provisioner: csi-cvmfsplugin
parameters:
  repository: atlas.cern.ch
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-cvmfs-cms
provisioner: csi-cvmfsplugin
parameters:
  repository: cms.cern.ch
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-cvmfs-atlas-pvc
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-cvmfs-atlas
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-cvmfs-cms-pvc
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-cvmfs-cms
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cvmfs
  labels:
    app: cvmfs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cvmfs
  template:
    metadata:
      labels:
        app: cvmfs
    spec:
      containers:
       - name: atlas
         image: busybox
         command: ["/bin/sh"]
         args: ["-c", "sleep 10000"]
         volumeMounts:
           - mountPath: /cvmfs/atlas.cern.ch
             name: atlas-pvc
       - name: cms
         image: busybox
         command: ["/bin/sh"]
         args: ["-c", "sleep 10000"]
         volumeMounts:
           - mountPath: /cvmfs/cms.cern.ch
             name: cms-pvc
      volumes:
      - name: atlas-pvc
        persistentVolumeClaim:
          claimName: csi-cvmfs-atlas-pvc
          readOnly: true
      - name: cms-pvc
        persistentVolumeClaim:
          claimName: csi-cvmfs-cms-pvc
          readOnly: true
