apiVersion: v1
kind: ConfigMap
metadata:
  name: cvmfs-csi-default-local
  labels:
    app: cvmfs-csi
data:
  default.local: |
    CVMFS_USE_GEOAPI=yes
    CVMFS_HTTP_PROXY="http://ca-proxy.cern.ch:3128"

    CVMFS_QUOTA_LIMIT=1000
    CVMFS_CACHE_BASE=/cvmfs-localcache
