kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: cvmfs-csi-nodeplugin
  labels:
    app: cvmfs-csi
    component: nodeplugin
spec:
  updateStrategy: 
    type: OnDelete
  selector:
    matchLabels:
      component: nodeplugin
      app: cvmfs-csi
  template:
    metadata:
      labels:
        app: cvmfs-csi
        component: nodeplugin
    spec:
      # hostPID is required for autofs to work.
      hostPID: true
      containers:
        - name: registrar
          image: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.5.1
          imagePullPolicy: IfNotPresent
          args:
            - -v=5
            - --csi-address=$(CSI_ADDRESS)
            - --kubelet-registration-path=$(KUBELET_CSI_REGISTRATION_PATH)
          env:
            - name: CSI_ADDRESS
              value: /csi/csi.sock
            - name: KUBELET_CSI_REGISTRATION_PATH
              value: /var/lib/kubelet/plugins/cvmfs.csi.cern.ch/csi.sock
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi
            - name: registration-dir
              mountPath: /registration
        - name: nodeplugin
          image: registry.cern.ch/magnum/cvmfs-csi:latest
          command: [/csi-cvmfsplugin]
          args:
            - -v=5
            - --nodeid=$(NODE_ID)
            - --endpoint=$(CSI_ENDPOINT)
            - --drivername=$(CSI_DRIVERNAME)
            - --role=identity,node
            - --automount-startup-timeout=10
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
          env:
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CSI_ENDPOINT
              value: unix:///var/lib/kubelet/plugins/cvmfs.csi.cern.ch/csi.sock
            - name: CSI_DRIVERNAME
              value: cvmfs.csi.cern.ch
          volumeMounts:
            - name: plugin-dir
              mountPath: /var/lib/kubelet/plugins/cvmfs.csi.cern.ch
            - name: pods-mount-dir
              mountPath: /var/lib/kubelet/pods
              mountPropagation: Bidirectional
            - mountPath: /sys
              name: host-sys
            - name: lib-modules
              mountPath: /lib/modules
              readOnly: true
            - name: host-dev
              mountPath: /dev
            - name: autofs-cvmfs
              mountPath: /cvmfs
              mountPropagation: Bidirectional
        - name: automount
          image: registry.cern.ch/magnum/cvmfs-csi:latest
          command:
            - /bin/bash
            - -c
            - |
              ulimit -n 1000000
              /automount-runner       \
                -v=5                  \
                --unmount-timeout=300 \
                --has-alien-cache=false
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
          volumeMounts:
            - mountPath: /sys
              name: host-sys
            - name: lib-modules
              mountPath: /lib/modules
              readOnly: true
            - name: host-dev
              mountPath: /dev
            - name: autofs-cvmfs
              mountPath: /cvmfs
              mountPropagation: Bidirectional
            - name: cvmfs-localcache
              mountPath: /cvmfs-localcache
            - name: etc-cvmfs-default-conf
              mountPath: /etc/cvmfs/default.local
              subPath: default.local
            - name: etc-cvmfs-config-d
              mountPath: /etc/cvmfs/config.d
      volumes:
        - name: plugin-dir
          hostPath:
            path: /var/lib/kubelet/plugins/cvmfs.csi.cern.ch
            type: DirectoryOrCreate
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry
            type: DirectoryOrCreate
        - name: pods-mount-dir
          hostPath:
            path: /var/lib/kubelet/pods
            type: Directory
        - name: host-sys
          hostPath:
            path: /sys
        - name: lib-modules
          hostPath:
            path: /lib/modules
        - name: host-dev
          hostPath:
            path: /dev
        - name: autofs-cvmfs
          emptyDir: {}
        - name: cvmfs-localcache
          emptyDir: {}
        - name: etc-cvmfs-default-conf
          configMap:
            name: cvmfs-csi-default-local
        - name: etc-cvmfs-config-d
          configMap:
            name: cvmfs-csi-config-d
      priorityClassName: system-node-critical
