apiVersion: v1
kind: Pod
metadata:
  name: web-server
spec:
  containers:
    - name: web-server
      image: nginx
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: cvmfs-mount
          mountPath: /cms-repository
        - name: cephfs-mount
          mountPath: /var/lib/www/html
  volumes:
    - name: cvmfs-mount
      persistentVolumeClaim:
        claimName: csi-cvmfs-pvc
        readOnly: true
    - name: cephfs-mount
      persistentVolumeClaim:
        claimName: csi-cephfs-pvc
        readOnly: false